name: Build Eaglercraft 1.12.2
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Runtime
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon
      - name: Upload Finished Client
        uses: actions/upload-artifact@v4
        with:
          name: Eagler-1.12-Client
          path: build/distributions/*.zip
